import { DashboardSettings } from "../types/dashboard";
import { defaultThemeSettings } from "./themeConfig";

export const defaultConfig: DashboardSettings = {
  title: "SmartHome Control",
  backgroundMode: "mesh",
  backgroundColor: "#08111f",
  backgroundAccent: "#123a5d",
  theme: defaultThemeSettings,
  grid: {
    columns: 12,
    rowHeight: 84,
    gap: 12,
  },
  pollingMs: 2000,
  iobroker: {
    baseUrl: "",
    adapterBasePath: "/smarthome-dashboard/api",
  },
  widgets: [
    {
      id: "front-door",
      type: "state",
      title: "Haustuer",
      stateId: "0_userdata.0.doors.front",
      writeable: true,
      onLabel: "Offen",
      offLabel: "Geschlossen",
      iconPair: {
        active: "door-open",
        inactive: "door-closed",
      },
      position: { x: 0, y: 0, w: 3, h: 2 },
    },
    {
      id: "alarm",
      type: "state",
      title: "Alarmanlage",
      stateId: "0_userdata.0.alarm.armed",
      writeable: true,
      onLabel: "Scharf",
      offLabel: "Unscharf",
      iconPair: {
        active: "shield-lock",
        inactive: "shield-off-outline",
      },
      position: { x: 3, y: 0, w: 3, h: 2 },
    },
    {
      id: "camera",
      type: "camera",
      title: "Einfahrt",
      snapshotUrl: "",
      rtspUrl: "rtsp://camera.local:554/stream1",
      refreshMs: 2000,
      position: { x: 6, y: 0, w: 6, h: 4 },
    },
    {
      id: "energy",
      type: "energy",
      title: "PV-Fluss",
      pvStateId: "0_userdata.0.energy.pv",
      houseStateId: "0_userdata.0.energy.house",
      batteryStateId: "0_userdata.0.energy.battery",
      gridStateId: "0_userdata.0.energy.grid",
      position: { x: 0, y: 2, w: 6, h: 3 },
    },
    {
      id: "ekd-solar",
      type: "solar",
      title: "Solar",
      statePrefix: "ekd-solar.0.friendly",
      keys: {
        pvNow: "leistung_pv_aktuell",
        homeNow: "hausverbrauch_aktuell",
        gridIn: "netzbezug_aktuell",
        gridOut: "netzeinspeisung_aktuell",
        soc: "ladezustand_akku",
        battIn: "ladeleistung_akku",
        battOut: "entladeleistung_akku",
        dayConsumed: "tagesverbrauch_gesamt",
        daySelf: "tages_eigenverbrauch_gesamt",
        pvTotal: "pv_ertrag_gesamt",
        battTemp: "akku_temp_bms1",
      },
      dailyEnergyUnit: "auto",
      position: { x: 0, y: 5, w: 12, h: 5 },
    },
  ],
};
